/**
 * Churn Risk API Handler
 *
 * Serves pre-computed churn dashboard data from churn-dashboard.json.
 * Data is generated by: cd churn-analyzer && node src/index.js report --dashboard
 */

const fs = require('fs');
const path = require('path');

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const dataPath = path.join(__dirname, '..', '..', 'dashboard', 'data', 'churn-dashboard.json');

  try {
    const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));
    res.json(data);
  } catch (err) {
    res.status(500).json({
      error: 'Churn data not generated yet. Run: cd churn-analyzer && node src/index.js report --dashboard',
    });
  }
};
